arb-dir: lib/l10n/translations
output-dir: lib/l10n/localizations
output-class: LocalizationsDesignSystemModule
output-localization-file: localizations_design_system_module.dart
template-arb-file: app_en.arb
use-escaping: true
synthetic-package: false